// applications/trade-journal/app/components/ImageSlot.vue
<script setup lang="ts">
import { fileToDataUrl, imageFileFromDrop, imageFileFromPaste } from '../lib/file'

const props = defineProps<{ label: string; relPath: string | null; canRemove?: boolean }>()
const emit = defineEmits<{ image: [string]; remove: [] }>()

const fileRef = ref<HTMLInputElement | null>(null)
const errored = ref(false)

watch(
  () => props.relPath,
  () => {
    errored.value = false
  },
)

const src = computed(() => useImageSrc(props.relPath))
const hasImage = computed(() => !!props.relPath && !errored.value)

async function onPaste(e: ClipboardEvent) {
  const file = imageFileFromPaste(e)
  if (file) {
    e.preventDefault()
    emit('image', await fileToDataUrl(file))
  }
}
async function onDrop(e: DragEvent) {
  e.preventDefault()
  const file = imageFileFromDrop(e)
  if (file) emit('image', await fileToDataUrl(file))
}
async function onPick(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0]
  if (file) emit('image', await fileToDataUrl(file))
  input.value = ''
}
</script>

<template>
  <div class="flex flex-col rounded-[10px] border border-default overflow-hidden bg-elevated/40">
    <div class="flex justify-between items-center px-3 py-1.5 border-b border-default">
      <span class="text-sm font-semibold text-dimmed">{{ label }}</span>
      <span
        v-if="hasImage && canRemove"
        class="text-xs text-primary cursor-pointer"
        @click="emit('remove')"
        >↻ 重新貼上</span
      >
    </div>

    <div
      tabindex="0"
      class="min-h-[170px] flex items-center justify-center outline-none"
      :class="hasImage ? 'cursor-default p-0' : 'cursor-pointer p-3'"
      @paste="onPaste"
      @drop="onDrop"
      @dragover.prevent
      @click="!hasImage && fileRef?.click()"
    >
      <img
        v-if="hasImage"
        :src="src"
        :alt="label"
        class="max-w-full max-h-[320px] block"
        @error="errored = true"
      />
      <div v-else-if="relPath && errored" class="flex flex-col items-center gap-1.5">
        <span class="text-xl">⚠️</span>
        <span class="text-sm text-dimmed">圖片遺失，可重新上傳</span>
      </div>
      <div v-else class="flex flex-col items-center gap-1.5">
        <span class="text-2xl">🖼</span>
        <span class="text-sm font-medium text-dimmed">貼上 {{ label }}</span>
        <span class="text-xs text-dimmed font-mono">Ctrl / ⌘ + V · 或拖放 · 或點擊選檔</span>
      </div>
    </div>

    <input ref="fileRef" type="file" accept="image/*" hidden @change="onPick" />
  </div>
</template>

// src/trade-journal/renderer/components/ImageSlot.tsx
import { useEffect, useRef, useState } from 'react'
import { Box, Group, Stack, Text } from '@mantine/core'
import { api } from '../api'
import { fileToDataUrl, imageFileFromDrop, imageFileFromPaste } from '../lib/file'

interface Props {
  label: string
  relPath: string | null
  onImage: (dataUrl: string) => void
  onRemove?: () => void
}

export function ImageSlot({ label, relPath, onImage, onRemove }: Props): JSX.Element {
  const [src, setSrc] = useState<string | null>(null)
  const [missing, setMissing] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    let alive = true
    if (relPath) {
      void api.images.readDataUrl(relPath).then((d) => {
        if (!alive) return
        setSrc(d)
        setMissing(d === null)
      })
    } else {
      setSrc(null)
      setMissing(false)
    }
    return () => {
      alive = false
    }
  }, [relPath])

  const handlePaste = async (e: React.ClipboardEvent): Promise<void> => {
    const file = imageFileFromPaste(e)
    if (file) {
      e.preventDefault()
      onImage(await fileToDataUrl(file))
    }
  }

  const handleDrop = async (e: React.DragEvent): Promise<void> => {
    e.preventDefault()
    const file = imageFileFromDrop(e)
    if (file) onImage(await fileToDataUrl(file))
  }

  const handlePick = async (e: React.ChangeEvent<HTMLInputElement>): Promise<void> => {
    const file = e.target.files?.[0]
    if (file) onImage(await fileToDataUrl(file))
    e.target.value = ''
  }

  const hasImage = !!relPath && !!src && !missing

  return (
    <Box
      style={{
        border: '1px solid var(--mantine-color-default-border)',
        borderRadius: 10,
        overflow: 'hidden',
        display: 'flex',
        flexDirection: 'column',
        background: 'var(--mantine-color-default)',
      }}
    >
      <Group justify="space-between" px="sm" py={6} style={{ borderBottom: '1px solid var(--mantine-color-default-border)' }}>
        <Text size="sm" fw={600} c="dimmed">
          {label}
        </Text>
        {hasImage && onRemove && (
          <Text size="xs" c="teal" style={{ cursor: 'pointer' }} onClick={onRemove}>
            ↻ 重新貼上
          </Text>
        )}
      </Group>

      <Box
        tabIndex={0}
        onPaste={handlePaste}
        onDrop={handleDrop}
        onDragOver={(e) => e.preventDefault()}
        onClick={() => {
          if (!hasImage) fileRef.current?.click()
        }}
        style={{
          minHeight: 170,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          cursor: hasImage ? 'default' : 'pointer',
          outline: 'none',
          padding: hasImage ? 0 : 12,
        }}
      >
        {hasImage ? (
          <img src={src as string} alt={label} style={{ maxWidth: '100%', maxHeight: 320, display: 'block' }} />
        ) : missing ? (
          <Stack align="center" gap={6}>
            <Text size="xl">⚠️</Text>
            <Text size="sm" c="dimmed">
              圖片遺失，可重新上傳
            </Text>
          </Stack>
        ) : (
          <Stack align="center" gap={6}>
            <Text size="28px">🖼</Text>
            <Text size="sm" fw={500} c="dimmed">
              貼上 {label}
            </Text>
            <Text size="xs" c="dimmed" ff="monospace">
              Ctrl / ⌘ + V · 或拖放 · 或點擊選檔
            </Text>
          </Stack>
        )}
      </Box>

      <input type="file" accept="image/*" hidden ref={fileRef} onChange={handlePick} />
    </Box>
  )
}
