// src/trade-journal/renderer/components/StatusBadge.tsx
import { Badge } from '@mantine/core'
import type { EntryStatus } from '@shared/domain'

const MAP: Record<EntryStatus, { color: string; label: string }> = {
  empty: { color: 'gray', label: '待記錄' },
  recorded: { color: 'yellow', label: '已記錄（待復盤）' },
  reviewed: { color: 'green', label: '已復盤' },
}

export function StatusBadge({ status }: { status: EntryStatus }): JSX.Element {
  const { color, label } = MAP[status]
  return (
    <Badge color={color} variant="light" radius="sm">
      {label}
    </Badge>
  )
}

// applications/trade-journal/app/components/StatusBadge.vue
<script setup lang="ts">
import type { EntryStatus } from '../../shared/domain'

const props = defineProps<{ status: EntryStatus }>()

const MAP: Record<EntryStatus, { color: 'neutral' | 'warning' | 'success'; label: string }> = {
  empty: { color: 'neutral', label: '待記錄' },
  recorded: { color: 'warning', label: '已記錄（待復盤）' },
  reviewed: { color: 'success', label: '已復盤' },
}

const meta = computed(() => MAP[props.status])
</script>

<template>
  <UBadge :color="meta.color" variant="subtle">{{ meta.label }}</UBadge>
</template>
